spring:
  datasource:
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.2.101:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G2QiAFRr173TQ863u5k
      secret-key: vRuZtlfrRynaxsy7VuexDMGoSUh7yd
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com

  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10001
logging:
  level:
    com.atguigu.gulimall: debug
